name: myAppBills
description: Solução Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  flutter_speed_dial: ^1.2.5
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.2
  progress_dialog: ^1.2.1
  http: ^0.12.0+4
  get_it: ^4.0.1
  package_info: ^0.4.0+17
  shared_preferences: ^0.5.7+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/ic_logo.png"
  image_path_android: "assets/images/ic_logo.png"

flutter_intl:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

    - family: Montserrat-Light
      fonts:
          - asset: assets/fonts/Montserrat-Light.ttf

    - family: Montserrat-Medium
      fonts:
            - asset: assets/fonts/Montserrat-Medium.ttf

    - family: Montserrat-Regular
      fonts:
            - asset: assets/fonts/Montserrat-Regular.ttf
